import hotel from "./modules/hotel";

const getters = {
  //user
  token: state => state.user.token,
  userId: state => state.user.userId,
  userInfo: state => state.user.userInfo,
  userOrderList: state => state.user.userOrderList,
  userReplyList: state => state.user.userReplyList,
  hotelListLoading: state => state.hotel.hotelListLoading,
  hotelList: state => state.hotel.hotelList,
  couponListForDisplay:state => state.hotel.couponListForDisplay,
  searchHotelList: state => state.hotel.searchHotelList,
  currentHotelInfo: state => state.hotel.currentHotelInfo,
  currentHotelId: state => state.hotel.currentHotelId,
  currentHotelComments :state => state.hotel.currentHotelComments,
  currentCommentsStatus :state => state.hotel.currentCommentsStatus,
  orderModalVisible: state => state.hotel.orderModalVisible,
  currentOrderRoom: state => state.hotel.currentOrderRoom,
  advertisementList:state=>state.hotel.advertisementList,
  isVipOfCurrentHotel : state=>state.hotel.isVipOfCurrentHotel,
  orderMatchCouponList: state => state.hotel.orderMatchCouponList,
  hotelFlag: state => state.hotel.hotelFlag,
  commentFlag: state => state.hotel.commentFlag,
  color: state => state.hotel.color,
  creditRechargeModalVisible: state => state.user.creditRechargeModalVisible,
  cancelOrderAppealModalVisible:state=>state.user.cancelOrderAppealModalVisible,
  appealOrderId:state=>state.user.appealOrderId,
  orderDetailCardVisible:state=>state.user.orderDetailCardVisible,
  currentOrderOfUser: state=>state.user.currentOrderOfUser,
  commentImgList: state=>state.hotel.commentImgList,
  atlasVisible: state=> state.hotel.atlasVisible,
  hotelListOfCurrentVIP:state=>state.user.hotelListOfCurrentVIP,
  imgList: state=> state.hotel.imgList,
  curHotelImg: state=> state.hotel.curHotelImg,
  historyOrderModalVisible:state=>state.user.historyOrderModalVisible,
  historyOrderList:state=>state.user.historyOrderList,
  //admin
  managerList: state => state.admin.managerList,
  addManagerModalVisible: state => state.admin.addManagerModalVisible,
  updateManagerModalVisible: state => state.admin.updateManagerModalVisible,
  addManagerParams: state => state.admin.addManagerParams,
  currentUserId: state => state.admin.currentUserId,
  currentUserParams: state => state.admin.currentUserParams,
  adManageList: state=>state.admin.adManageList,
  bindADHotelModalVisible:state=>state.admin.bindADHotelModalVisible,
  matchedHotelList:state=>state.admin.matchedHotelList,
  currentADId:state=>state.admin.currentADId,
  webVIPList:state=>state.admin.webVIPList,
  webVIPcouponModalVisible:state=>state.admin.webVIPcouponModalVisible,
  webVIPCouponList:state=>state.admin.webVIPCouponList,
  //hotelManager
  // orderList: state => state.hotelManager.orderList,这个是所有的Order的list
  orderListOfCurrentHotel:state=>state.hotelManager.orderListOfCurrentHotel,
  addHotelModalVisible: state => state.hotelManager.addHotelModalVisible,
  updateHotelModalVisible: state => state.hotelManager.updateHotelModalVisible,
  updateRoomModalVisible: state => state.hotelManager.updateRoomModalVisible,
  addRoomModalVisible: state => state.hotelManager.addRoomModalVisible,
  couponVisible: state => state.hotelManager.couponVisible,
  addCouponVisible: state => state.hotelManager.addCouponVisible,
  hotelImgList: state => state.hotel.hotelImgList,
  userImgList: state => state.hotel.userImgList,
  couponList: state => state.hotelManager.couponList,
  appealReviewModalVisible: state=> state.hotelManager.appealReviewModalVisible,
  appealMessageReview: state=>state.hotelManager.appealMessageReview,
  appealReviewOrderId:state=>state.hotelManager.appealReviewOrderId,
  appealCreditRechargeimfo:state=>state.hotelManager.appealCreditRechargeimfo,
  currentOrderOfHM:state=>state.hotelManager.currentOrderOfHM,
  orderDetailCardVisibleHM:state=>state.hotelManager.orderDetailCardVisibleHM,
  webCoupon:state=>state.hotelManager.webCoupon,
  webCouponList:state=>state.hotelManager.webCouponList,
  hotelImgUrl:state=>state.hotelManager.hotelImgUrl,
  roomImgUrl:state=>state.hotelManager.roomImgUrl,
  vipListOfCurrentHotel:state=>state.hotelManager.vipListOfCurrentHotel
  }
  
  export default getters